#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
setup_wizard.py — Interactive setup for fileiotest configuration.

Generates config.toml with site-specific machine names, IPs, and paths.
Optionally validates SSH connectivity to all machines.

Usage:
    python3 setup_wizard.py
    python3 setup_wizard.py --no-validate   # skip SSH checks
"""

__author__ = 'João Tonini'
__version__ = '0.3'

import argparse
import os
import shutil
import subprocess
import sys

CONFIG_FILE = 'config.toml'


def ask(prompt: str, default: str = '') -> str:
    if default:
        raw = input(f"  {prompt} [{default}]: ").strip()
        return raw if raw else default
    else:
        while True:
            raw = input(f"  {prompt}: ").strip()
            if raw:
                return raw
            print("    (required)")


def ask_list(prompt: str, hint: str = '') -> list:
    if hint:
        print(f"  {hint}")
    while True:
        raw = input(f"  {prompt}: ").strip()
        if raw:
            items = [x.strip() for x in raw.replace(',', ' ').split() if x.strip()]
            if items:
                return items
        print("    (at least one value required)")


def ask_int(prompt: str, default: int) -> int:
    while True:
        raw = input(f"  {prompt} [{default}]: ").strip()
        if not raw:
            return default
        try:
            return int(raw)
        except ValueError:
            print("    (must be a number)")


def ask_yn(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    raw = input(f"  {prompt} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw in ('y', 'yes')


def validate_ssh(user: str, host: str) -> bool:
    try:
        result = subprocess.run(
            ['ssh', '-o', 'ConnectTimeout=5', '-o', 'BatchMode=yes',
             f'{user}@{host}', 'echo ok'],
            capture_output=True, text=True, timeout=10
        )
        return result.returncode == 0 and 'ok' in result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


def write_config(config: dict):
    machines_str = ',\n    '.join(f'"{m}"' for m in config['switch_machines'])

    content = f'''# fileiotest configuration
# Generated by setup_wizard.py
# NOTE: This file contains site-specific information.
#       Do NOT commit to version control.

[destination]
machine = "{config['dest_machine']}"
user = "{config['dest_user']}"

[wire]
source_machine = "{config['wire_source']}"
user = "{config['wire_user']}"
dest_ip = "{config['wire_dest_ip']}"
source_ip = "{config['wire_source_ip']}"

[source]
switch_machines = [
    {machines_str},
]
user = "{config['switch_user']}"

[paths]
deploy_dir = "{config['deploy_dir']}"
results_dir = "{config['results_dir']}"

[collection]
num_files = "{config['num_files']}"
interval_min = {config['interval_min']}
duration_hr = {config['duration_hr']}
ping_count = {config['ping_count']}
'''
    with open(CONFIG_FILE, 'w') as f:
        f.write(content)


def main():
    parser = argparse.ArgumentParser(description='Interactive fileiotest setup')
    parser.add_argument('--no-validate', action='store_true',
                        help='Skip SSH connectivity validation')
    args = parser.parse_args()

    # Clear screen
    os.system('clear')

    print()
    print("╔══════════════════════════════════════════════════════════════╗")
    print("║  fileiotest Setup Wizard                                    ║")
    print("║  Generates config.toml with your lab configuration.         ║")
    print("╚══════════════════════════════════════════════════════════════╝")
    print()

    if os.path.exists(CONFIG_FILE):
        if not ask_yn(f"{CONFIG_FILE} already exists. Overwrite?", default=False):
            print("  Aborted.")
            sys.exit(0)
        backup = f"{CONFIG_FILE}.bak"
        shutil.copy2(CONFIG_FILE, backup)
        print(f"  (backed up to {backup})")
    print()

    config = {}

    # ─── Destination ──────────────────────────────────────────────────
    print("─── Destination Machine ────────────────────────────────────")
    print("  The machine that receives all transfers (both wire and")
    print("  switch tests send data to this machine).")
    print()
    config['dest_machine'] = ask("Destination hostname")
    config['dest_user'] = ask("SSH username on destination",
                              default=os.environ.get('USER', ''))
    print()

    # ─── Wire connection ──────────────────────────────────────────────
    print("─── Direct Wire Connection ─────────────────────────────────")
    print("  The point-to-point Ethernet link between two machines.")
    print("  This uses a private IP subnet (e.g., 10.0.0.x).")
    print()
    config['wire_source'] = ask("Wire source machine hostname (sender)")
    config['wire_user'] = ask("SSH username for wire test",
                              default=config['dest_user'])
    config['wire_dest_ip'] = ask("Destination IP on the wire (receiver end)",
                                 default="10.0.0.1")
    config['wire_source_ip'] = ask("Source IP on the wire (sender end)",
                                   default="10.0.0.2")
    print()
    print(f"  Wire topology: {config['wire_source']} ({config['wire_source_ip']})")
    print(f"                  ──── Cat5e ────")
    print(f"                 {config['dest_machine']} ({config['wire_dest_ip']})")
    print()

    # ─── Switch machines ──────────────────────────────────────────────
    print("─── University Switch Sources ──────────────────────────────")
    print("  Workstations that connect to the destination through the")
    print("  university network switch.")
    print(f"  (Do NOT include the destination '{config['dest_machine']}' here.)")
    print()
    config['switch_user'] = ask("SSH username for switch tests",
                                default=config['dest_user'])
    raw_machines = ask_list(
        "Machine hostnames (space or comma separated)",
        hint="    e.g.: host1 host2 host3 host4 host5 host6"
    )

    # Remove destination if accidentally included
    dest = config['dest_machine']
    filtered = [m for m in raw_machines if m != dest]
    if len(filtered) < len(raw_machines):
        print(f"\n  NOTE: Removed '{dest}' from switch sources — a machine")
        print(f"  cannot send to itself.")
    config['switch_machines'] = filtered

    if not config['switch_machines']:
        print("  ERROR: No switch sources remain after removing destination.")
        sys.exit(1)

    print()
    total = 1 + len(config['switch_machines'])
    print(f"  Total: {total} source machines → {config['dest_machine']}")
    print(f"    Wire:          {config['wire_source']} → {config['wire_dest_ip']}"
          f"  (as {config['wire_user']})")
    print(f"    Switch ({len(config['switch_machines']):2d}):   "
          f"{', '.join(config['switch_machines'])} → {config['dest_machine']}"
          f"  (as {config['switch_user']})")
    print()

    # ─── Paths ────────────────────────────────────────────────────────
    print("─── Paths ──────────────────────────────────────────────────")
    config['deploy_dir'] = ask("Deploy directory on source machines",
                               default="~/fileiotest")
    config['results_dir'] = ask("Results subdirectory",
                                default="./collector_results")
    print()

    # ─── Collection parameters ────────────────────────────────────────
    print("─── Collection Parameters ──────────────────────────────────")
    config['num_files'] = ask("File counts to cycle (comma-separated)",
                              default="10")
    config['interval_min'] = ask_int("Interval between samples (minutes)",
                                     default=15)
    config['duration_hr'] = ask_int("Total collection duration (hours)",
                                    default=168)
    config['ping_count'] = ask_int("Pings per sample", default=20)
    print()

    # ─── Validate SSH ─────────────────────────────────────────────────
    if not args.no_validate:
        print("─── Validating SSH Connectivity ────────────────────────────")
        print()

        failures = []

        # Destination
        label = f"{config['dest_user']}@{config['dest_machine']}"
        sys.stdout.write(f"  {label:30s} ")
        sys.stdout.flush()
        if validate_ssh(config['dest_user'], config['dest_machine']):
            print("✓  (destination)")
        else:
            print("✗  (SSH failed)")
            failures.append(config['dest_machine'])

        # Switch sources
        for host in config['switch_machines']:
            label = f"{config['switch_user']}@{host}"
            sys.stdout.write(f"  {label:30s} ")
            sys.stdout.flush()
            if validate_ssh(config['switch_user'], host):
                print("✓  (campus)")
            else:
                print("✗  (SSH failed)")
                failures.append(host)

        # Wire machine — may only be reachable from the current host
        host = config['wire_source']
        label = f"{config['wire_user']}@{host}"
        sys.stdout.write(f"  {label:30s} ")
        sys.stdout.flush()
        if validate_ssh(config['wire_user'], host):
            print("✓  (campus)")
        else:
            print("?  (may only be reachable locally)")

        # Wire destination IP — likely only reachable from wire source
        label = f"{config['wire_user']}@{config['wire_dest_ip']}"
        sys.stdout.write(f"  {label:30s} ")
        sys.stdout.flush()
        if validate_ssh(config['wire_user'], config['wire_dest_ip']):
            print("✓  (wire)")
        else:
            print("?  (only reachable from {})".format(config['wire_source']))

        print()
        if failures:
            print(f"  WARNING: SSH failed for {len(failures)} host(s): "
                  f"{', '.join(failures)}")
            print("  Make sure passwordless SSH is configured (ssh-copy-id).")
            print()
            if not ask_yn("Continue anyway?", default=True):
                print("  Aborted. Fix SSH and re-run the wizard.")
                sys.exit(1)
        else:
            print("  All campus hosts reachable. Wire IPs checked above.")
        print()

    # ─── Write config ─────────────────────────────────────────────────
    write_config(config)
    print(f"  ✓ Configuration written to {CONFIG_FILE}")
    print()

    # ─── .gitignore ───────────────────────────────────────────────────
    gitignore = '.gitignore'
    needs_entry = True
    if os.path.exists(gitignore):
        with open(gitignore, 'r') as f:
            if CONFIG_FILE in f.read():
                needs_entry = False
    if needs_entry:
        with open(gitignore, 'a') as f:
            f.write(f"\n# Site-specific config — do not commit\n{CONFIG_FILE}\n")
        print(f"  ✓ Added {CONFIG_FILE} to .gitignore")
    else:
        print(f"  ✓ {CONFIG_FILE} already in .gitignore")

    print()
    print("  You're ready to go!")
    print()
    print("  For switch machines (from any campus machine):")
    print("    ./orchestrator.sh start")
    print()
    print(f"  For the wire test (from {config['wire_source']} directly):")
    print(f"    cd {config['deploy_dir']}")
    print(f"    nohup env \\")
    print(f"      SOURCE_LABEL='{config['wire_source']}' \\")
    print(f"      DEST_CACHE_SSH='{config['wire_user']}@{config['wire_dest_ip']}' \\")
    print(f"    bash ./collector.sh "
          f"'{config['wire_user']}@{config['wire_dest_ip']}' \\")
    print(f"      > collector_{config['wire_source']}.log 2>&1 &")
    print()


if __name__ == '__main__':
    main()
